### ISSUE TITLE
cannot refference task parametters inside HttpAction url 

### ISSUE THREAD

**Issue by bylidev** [dopplertask/dopplertask#35]
I am having an error using taskParameters inside the url. I also wanted to tell you that I am very happy to have found this tool !

java.lang.IllegalArgumentException: Illegal character in query at index 115: .../api/v1/onboarding_sessions?loan_application_id=$parameters.get("loanid")
![image](https://user-images.githubusercontent.com/43254184/198696197-3cbfb941-ab89-47ae-bc35-762787463a0e.png)

**Comment by igloar96** [comment]
i think it was produced by this error
`org.springframework.jms.listener.adapter.ListenerExecutionFailedException: Listener method 'public void com.dopplertask.dopplertask.service.TaskServiceImpl.handleAutomationRequest(com.dopplertask.dopplertask.service.TaskExecutionRequest)' threw exception; nested exception is org.hibernate.HibernateException: More than one row with the given identifier was found: 134, for class: com.dopplertask.dopplertask.domain.Connection
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:122) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.13.jar!/:5.3.13]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
Caused by: org.hibernate.HibernateException: More than one row with the given identifier was found: 134, for class: com.dopplertask.dopplertask.domain.Connection
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:104) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:66) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.loadByUniqueKey(AbstractEntityPersister.java:2486) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.type.EntityType.loadByUniqueKey(EntityType.java:756) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.type.EntityType.resolve(EntityType.java:467) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad$EntityResolver.lambda$static$0(TwoPhaseLoad.java:576) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntityEntryLoadedState(TwoPhaseLoad.java:221) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:155) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:126) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.performTwoPhaseLoad(AbstractRowReader.java:221) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:187) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:96) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:105) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:87) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:710) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:76) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2217) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:595) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:787) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1001) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:987) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:130) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:87) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:710) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:76) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2217) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:595) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:149) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:387) ~[hibernate-core-5.6.1.Final.jar!/:5.6.1.Final]
	at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821) ~[na:na]
	at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at com.dopplertask.dopplertask.domain.Task.getWebhookStartAction(Task.java:132) ~[classes!/:na]
	at com.dopplertask.dopplertask.service.ExecutionServiceImpl.processActions(ExecutionServiceImpl.java:328) ~[classes!/:na]
	at com.dopplertask.dopplertask.service.ExecutionServiceImpl$$FastClassBySpringCGLIB$$bf833df9.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.13.jar!/:5.3.13]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.13.jar!/:5.3.13]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at com.dopplertask.dopplertask.service.ExecutionServiceImpl$$EnhancerBySpringCGLIB$$f8793590.processActions(<generated>) ~[classes!/:na]
	at com.dopplertask.dopplertask.service.TaskServiceImpl.runRequest(TaskServiceImpl.java:115) ~[classes!/:na]
	at com.dopplertask.dopplertask.service.TaskServiceImpl.handleAutomationRequest(TaskServiceImpl.java:91) ~[classes!/:na]
	at com.dopplertask.dopplertask.service.TaskServiceImpl$$FastClassBySpringCGLIB$$eb520c74.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.13.jar!/:5.3.13]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.13.jar!/:5.3.13]
	at com.dopplertask.dopplertask.service.TaskServiceImpl$$EnhancerBySpringCGLIB$$e05105e1.handleAutomationRequest(<generated>) ~[classes!/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.13.jar!/:5.3.13]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.13.jar!/:5.3.13]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.3.13.jar!/:5.3.13]
	... 10 common frames omitted`

**Comment by feraswilson** [comment]
Hi, very glad that you found this tool helpful. Check that loadid is being set.

**Comment by bylidev** [comment]
The parameter was marked as "required", and when displaying it as a placeholder, I did not realize thatit was missing and did not take the default value.


![image](https://user-images.githubusercontent.com/43254184/198699301-01099c6d-95a1-48d0-98c1-73d595b9cf02.png)
![image](https://user-images.githubusercontent.com/43254184/198699499-0fc58029-229c-43a1-a172-0180f047cb52.png)
solved by filling parameter value 
![image](https://user-images.githubusercontent.com/43254184/198699997-f09a568e-0974-4c2b-8d55-d81f0ae68e2f.png)

Thanks.
